### PR TITLE
Add Widgets extension

### PR DESCRIPTION
**Pull request by jcfr**
This extension will allow to easily embed and configure a google calendar
widget.

See https://www.mediawiki.org/wiki/Extension:Widgets#Configuration

Note that since the extension requires that the "compiled_templates" to
exist and be writable by the web server, the "install_extensions" role
has been updated to check for the "writable_dirs" attribute.

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @pieper @fedorov @mhalle

**Comment by jcfr** [comment]
Note: I have **NOT** tested this

**Review by freephile — APPROVED** [review]
Thanks

**Comment by jcfr** [comment]
@freephile  Does this mean you have tested and it is good for integration ?

**Comment by freephile** [comment]
@jcfr I didn't test, but visually it looks good and I've got to add a bunch more extensions so they'll receive some scrutiny then.

**Comment by jcfr** [comment]
Sounds good. Note that I am fairly new to ansible.

**Pull request merged**
